version: "3"

services:
  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-viajesparatiproject}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-root}
    volumes:
      - database_data:/var/lib/mysql:rw

  symfony:
    image: php:7.4-apache
    volumes:
      - ./my_project_name:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - database

volumes:
  database_data:
